

#define PPG_ANALOG_INPUT_PIN  0   // PPG Signal Pin number

int NEXT_PPG_SAMPLE = 0;          // 
bool NEW_DATA = false;

int FILTERED_NEXT_PPG = 0;

void setup() {
  // set timer1 to 200 Hz

  TCCR1A = 0; // set TCCR2A register to 0
  TCCR1B = 0; // same for TCCR2B
  TCNT1  = 0; //initialize counter value to 0
  // set compare match register for 200 Hz increments
  OCR1A = 77; // 77.125 = (16*10^6) / (200*1024) - 1 (must be <65536)
  // turn on CTC mode
  TCCR1B |= (1 << WGM12);
  // Set CS12 and CS10 bits for 1024 prescaler
  TCCR1B |= (1 << CS12) | (1 << CS10);  
  // enable timer compare interrupt
  TIMSK1 |= (1 << OCIE1A);

  // starting serial connection with 115200 baud
  Serial.begin(115200);
}

void loop() {
  if (NEW_DATA) {
    NEW_DATA = false;
    FILTERED_NEXT_PPG = FILTERED_NEXT_PPG * 0.85 + NEXT_PPG_SAMPLE * 0.15;  // implements crude low pass filter
    Serial.print(">PPG:");
    Serial.println(FILTERED_NEXT_PPG);
  }
}

/*
  ISR generated by Timer 1
  Timer 1 timeouts for a 200 Hz pulse
  Toggles...
*/
ISR(TIMER1_COMPA_vect) {
  //timer1 interrupt 1Hz toggles pin 13 (LED)
  //generates pulse wave of frequency 1Hz/2 = 0.5kHz (takes two cycles for full wave- toggle high then toggle low)
  NEW_DATA = true;
  NEXT_PPG_SAMPLE = analogRead(PPG_ANALOG_INPUT_PIN);
}